// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Summarizes client testimonials and highlights positive sentiments.
 *
 * - summarizeTestimonial - A function that handles the testimonial summarization process.
 * - SummarizeTestimonialInput - The input type for the summarizeTestimonial function.
 * - SummarizeTestimonialOutput - The return type for the summarizeTestimonial function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SummarizeTestimonialInputSchema = z.object({
  testimonial: z
    .string()
    .describe('The client testimonial to be summarized.'),
});
export type SummarizeTestimonialInput = z.infer<typeof SummarizeTestimonialInputSchema>;

const SummarizeTestimonialOutputSchema = z.object({
  summary: z
    .string()
    .describe('A concise summary of the client testimonial, highlighting positive sentiments.'),
});
export type SummarizeTestimonialOutput = z.infer<typeof SummarizeTestimonialOutputSchema>;

export async function summarizeTestimonial(
  input: SummarizeTestimonialInput
): Promise<SummarizeTestimonialOutput> {
  return summarizeTestimonialFlow(input);
}

const summarizeTestimonialPrompt = ai.definePrompt({
  name: 'summarizeTestimonialPrompt',
  input: {schema: SummarizeTestimonialInputSchema},
  output: {schema: SummarizeTestimonialOutputSchema},
  prompt: `Summarize the following client testimonial, highlighting the positive sentiments expressed. The summary should be concise and engaging for potential clients.\n\nTestimonial: {{{testimonial}}}`,
});

const summarizeTestimonialFlow = ai.defineFlow(
  {
    name: 'summarizeTestimonialFlow',
    inputSchema: SummarizeTestimonialInputSchema,
    outputSchema: SummarizeTestimonialOutputSchema,
  },
  async input => {
    const {output} = await summarizeTestimonialPrompt(input);
    return output!;
  }
);
